version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ./.env
  web:
    image: jliussup/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  postgres_db:
